# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enginetargetlanes.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2
import reserved_pb2 as reserved__pb2
import pose_pb2 as pose__pb2
import geometry_pb2 as geometry__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='enginetargetlanes.proto',
  package='atd.map',
  syntax='proto2',
  serialized_pb=_b('\n\x17\x65nginetargetlanes.proto\x12\x07\x61td.map\x1a\x0cheader.proto\x1a\x0ereserved.proto\x1a\npose.proto\x1a\x0egeometry.proto\"\x96\x01\n\x12LaneChangeDecision\x12\x0e\n\x06leftBG\x18\x01 \x01(\x05\x12\x10\n\x08\x63\x65nterBG\x18\x02 \x01(\x05\x12\x0f\n\x07rightBG\x18\x03 \x01(\x05\x12\x14\n\x0cRemainLength\x18\x04 \x01(\x02\x12\x1a\n\x12leftTurnAreaLength\x18\x05 \x01(\x02\x12\x1b\n\x13rightTurnAreaLength\x18\x06 \x01(\x02\"\x8f\x01\n\nTargetLane\x12\r\n\x05\x62Line\x18\x01 \x01(\x08\x12\x11\n\tnLineType\x18\x02 \x01(\x05\x12\x14\n\x0cnArrayLength\x18\x03 \x01(\x05\x12\"\n\x05point\x18\x04 \x03(\x0b\x32\x13.atd.common.Point2D\x12%\n\x08point_EC\x18\x05 \x03(\x0b\x32\x13.atd.common.Point2D\"\xa7\x02\n\x0bTargetArrow\x12\r\n\x05level\x18\x01 \x01(\x05\x12\x12\n\nguide_info\x18\x02 \x01(\x05\x12(\n\x0btargetarrow\x18\x03 \x01(\x0b\x32\x13.atd.common.Arrow2D\x12\x13\n\x0btarget_diff\x18\x05 \x01(\x01\x12\'\n\ncenterlane\x18\x06 \x03(\x0b\x32\x13.atd.common.Arrow2D\x12%\n\x08leftlane\x18\x07 \x03(\x0b\x32\x13.atd.common.Point2D\x12&\n\trightlane\x18\x08 \x03(\x0b\x32\x13.atd.common.Point2D\x12\r\n\x05index\x18\t \x01(\x05\x12\x16\n\x0einflow_indexes\x18\n \x03(\x05\x12\x17\n\x0foutflow_indexes\x18\x0b \x03(\x05\"\x86\x03\n\x11\x45ngineTargetLanes\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.atd.common.header\x12)\n\x0breservedmsg\x18\x02 \x01(\x0b\x32\x14.atd.common.Reserved\x12$\n\x04pose\x18\x03 \x01(\x0b\x32\x16.atd.localization.Pose\x12)\n\x0cleftleftlane\x18\x04 \x01(\x0b\x32\x13.atd.map.TargetLane\x12%\n\x08leftlane\x18\x05 \x01(\x0b\x32\x13.atd.map.TargetLane\x12&\n\trightlane\x18\x06 \x01(\x0b\x32\x13.atd.map.TargetLane\x12+\n\x0erightrightlane\x18\x07 \x01(\x0b\x32\x13.atd.map.TargetLane\x12/\n\nlanechange\x18\x08 \x01(\x0b\x32\x1b.atd.map.LaneChangeDecision\x12$\n\x06target\x18\t \x03(\x0b\x32\x14.atd.map.TargetArrowB\x02H\x03')
  ,
  dependencies=[header__pb2.DESCRIPTOR,reserved__pb2.DESCRIPTOR,pose__pb2.DESCRIPTOR,geometry__pb2.DESCRIPTOR,])




_LANECHANGEDECISION = _descriptor.Descriptor(
  name='LaneChangeDecision',
  full_name='atd.map.LaneChangeDecision',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='leftBG', full_name='atd.map.LaneChangeDecision.leftBG', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='centerBG', full_name='atd.map.LaneChangeDecision.centerBG', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rightBG', full_name='atd.map.LaneChangeDecision.rightBG', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RemainLength', full_name='atd.map.LaneChangeDecision.RemainLength', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='leftTurnAreaLength', full_name='atd.map.LaneChangeDecision.leftTurnAreaLength', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rightTurnAreaLength', full_name='atd.map.LaneChangeDecision.rightTurnAreaLength', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=245,
)


_TARGETLANE = _descriptor.Descriptor(
  name='TargetLane',
  full_name='atd.map.TargetLane',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bLine', full_name='atd.map.TargetLane.bLine', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nLineType', full_name='atd.map.TargetLane.nLineType', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nArrayLength', full_name='atd.map.TargetLane.nArrayLength', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='point', full_name='atd.map.TargetLane.point', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='point_EC', full_name='atd.map.TargetLane.point_EC', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=391,
)


_TARGETARROW = _descriptor.Descriptor(
  name='TargetArrow',
  full_name='atd.map.TargetArrow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='level', full_name='atd.map.TargetArrow.level', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='guide_info', full_name='atd.map.TargetArrow.guide_info', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='targetarrow', full_name='atd.map.TargetArrow.targetarrow', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_diff', full_name='atd.map.TargetArrow.target_diff', index=3,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='centerlane', full_name='atd.map.TargetArrow.centerlane', index=4,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='leftlane', full_name='atd.map.TargetArrow.leftlane', index=5,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rightlane', full_name='atd.map.TargetArrow.rightlane', index=6,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='index', full_name='atd.map.TargetArrow.index', index=7,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inflow_indexes', full_name='atd.map.TargetArrow.inflow_indexes', index=8,
      number=10, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='outflow_indexes', full_name='atd.map.TargetArrow.outflow_indexes', index=9,
      number=11, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=394,
  serialized_end=689,
)


_ENGINETARGETLANES = _descriptor.Descriptor(
  name='EngineTargetLanes',
  full_name='atd.map.EngineTargetLanes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='atd.map.EngineTargetLanes.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reservedmsg', full_name='atd.map.EngineTargetLanes.reservedmsg', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pose', full_name='atd.map.EngineTargetLanes.pose', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='leftleftlane', full_name='atd.map.EngineTargetLanes.leftleftlane', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='leftlane', full_name='atd.map.EngineTargetLanes.leftlane', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rightlane', full_name='atd.map.EngineTargetLanes.rightlane', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rightrightlane', full_name='atd.map.EngineTargetLanes.rightrightlane', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lanechange', full_name='atd.map.EngineTargetLanes.lanechange', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target', full_name='atd.map.EngineTargetLanes.target', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=692,
  serialized_end=1082,
)

_TARGETLANE.fields_by_name['point'].message_type = geometry__pb2._POINT2D
_TARGETLANE.fields_by_name['point_EC'].message_type = geometry__pb2._POINT2D
_TARGETARROW.fields_by_name['targetarrow'].message_type = geometry__pb2._ARROW2D
_TARGETARROW.fields_by_name['centerlane'].message_type = geometry__pb2._ARROW2D
_TARGETARROW.fields_by_name['leftlane'].message_type = geometry__pb2._POINT2D
_TARGETARROW.fields_by_name['rightlane'].message_type = geometry__pb2._POINT2D
_ENGINETARGETLANES.fields_by_name['header'].message_type = header__pb2._HEADER
_ENGINETARGETLANES.fields_by_name['reservedmsg'].message_type = reserved__pb2._RESERVED
_ENGINETARGETLANES.fields_by_name['pose'].message_type = pose__pb2._POSE
_ENGINETARGETLANES.fields_by_name['leftleftlane'].message_type = _TARGETLANE
_ENGINETARGETLANES.fields_by_name['leftlane'].message_type = _TARGETLANE
_ENGINETARGETLANES.fields_by_name['rightlane'].message_type = _TARGETLANE
_ENGINETARGETLANES.fields_by_name['rightrightlane'].message_type = _TARGETLANE
_ENGINETARGETLANES.fields_by_name['lanechange'].message_type = _LANECHANGEDECISION
_ENGINETARGETLANES.fields_by_name['target'].message_type = _TARGETARROW
DESCRIPTOR.message_types_by_name['LaneChangeDecision'] = _LANECHANGEDECISION
DESCRIPTOR.message_types_by_name['TargetLane'] = _TARGETLANE
DESCRIPTOR.message_types_by_name['TargetArrow'] = _TARGETARROW
DESCRIPTOR.message_types_by_name['EngineTargetLanes'] = _ENGINETARGETLANES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LaneChangeDecision = _reflection.GeneratedProtocolMessageType('LaneChangeDecision', (_message.Message,), dict(
  DESCRIPTOR = _LANECHANGEDECISION,
  __module__ = 'enginetargetlanes_pb2'
  # @@protoc_insertion_point(class_scope:atd.map.LaneChangeDecision)
  ))
_sym_db.RegisterMessage(LaneChangeDecision)

TargetLane = _reflection.GeneratedProtocolMessageType('TargetLane', (_message.Message,), dict(
  DESCRIPTOR = _TARGETLANE,
  __module__ = 'enginetargetlanes_pb2'
  # @@protoc_insertion_point(class_scope:atd.map.TargetLane)
  ))
_sym_db.RegisterMessage(TargetLane)

TargetArrow = _reflection.GeneratedProtocolMessageType('TargetArrow', (_message.Message,), dict(
  DESCRIPTOR = _TARGETARROW,
  __module__ = 'enginetargetlanes_pb2'
  # @@protoc_insertion_point(class_scope:atd.map.TargetArrow)
  ))
_sym_db.RegisterMessage(TargetArrow)

EngineTargetLanes = _reflection.GeneratedProtocolMessageType('EngineTargetLanes', (_message.Message,), dict(
  DESCRIPTOR = _ENGINETARGETLANES,
  __module__ = 'enginetargetlanes_pb2'
  # @@protoc_insertion_point(class_scope:atd.map.EngineTargetLanes)
  ))
_sym_db.RegisterMessage(EngineTargetLanes)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
