# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reserved.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='reserved.proto',
  package='atd.common',
  syntax='proto2',
  serialized_pb=_b('\n\x0ereserved.proto\x12\natd.common\"6\n\x08Reserved\x12\x14\n\x0creserved_msg\x18\x01 \x01(\t\x12\x14\n\x0creserved_bit\x18\x02 \x01(\tB\x02H\x03')
)




_RESERVED = _descriptor.Descriptor(
  name='Reserved',
  full_name='atd.common.Reserved',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reserved_msg', full_name='atd.common.Reserved.reserved_msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reserved_bit', full_name='atd.common.Reserved.reserved_bit', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['Reserved'] = _RESERVED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Reserved = _reflection.GeneratedProtocolMessageType('Reserved', (_message.Message,), dict(
  DESCRIPTOR = _RESERVED,
  __module__ = 'reserved_pb2'
  # @@protoc_insertion_point(class_scope:atd.common.Reserved)
  ))
_sym_db.RegisterMessage(Reserved)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
