"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class HEADER(object):
    __slots__ = ["nTimeStamp", "nFrameID", "nCounter"]

    __typenames__ = ["int64_t", "byte", "int32_t"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.nTimeStamp = 0
        self.nFrameID = 0
        self.nCounter = 0

    def encode(self):
        buf = BytesIO()
        buf.write(HEADER._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qBi", self.nTimeStamp, self.nFrameID, self.nCounter))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != HEADER._get_packed_fingerprint():
            raise ValueError("Decode error")
        return HEADER._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = HEADER()
        self.nTimeStamp, self.nFrameID, self.nCounter = struct.unpack(">qBi", buf.read(13))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if HEADER in parents: return 0
        tmphash = (0x946e13e832aae58f) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if HEADER._packed_fingerprint is None:
            HEADER._packed_fingerprint = struct.pack(">Q", HEADER._get_hash_recursive([]))
        return HEADER._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

